listener {
    timeout = 300        
    on-timeout = hyprlock -q > /dev/null 2>&1 
    on-resume = 
}

listener {
    timeout = 600       
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on
}
