# AUTOGENERATED - DO NOT EDIT
# Sourced from the bottom of hyprland.conf so these win over the values above.
#
# Only the theme-varying parts live here. Geometry (gaps, border_size,
# rounding, opacity, blur) is identical across all ten themes, so it stays
# hand-tuned in hyprland.conf rather than being overwritten on every switch.

general {
  col.active_border = {{border_active_grad}}
  col.inactive_border = {{border_inactive_soft}}
}

# Layer rules
layerrule = blur on, match:namespace quickshell:bar
layerrule = ignore_alpha 0.2, match:namespace quickshell:bar

layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0.2, match:namespace wofi

layerrule = blur on, match:class wleave
layerrule = ignore_alpha 0.2, match:class wleave

# Hyprshot selection fix
layerrule = blur off, match:namespace selection
