/* AUTOGENERATED - DO NOT EDIT
   ==========================================================================
   Shared desktop chrome.

   Rendered by ~/.config/theme-switcher/apply-theme.sh on every theme switch.
   Any GTK app that should look like the rest of the desktop imports it as the
   very first line of its stylesheet (GTK requires @import before any rule):

       @import url("file://{{chrome_css}}");

   Then use the @chrome_* colours below instead of hardcoding hex.

   Why colours only: GTK3 (wofi) has no custom properties, so lengths cannot be
   shared as variables the way colours can - @define-color is the one construct
   both GTK3 and GTK4 understand. The numeric rhythm is therefore written out
   here once as the reference, and repeated literally by each consumer.

   Rhythm, taken from the swaync control center:
     radius    12px  panels and cards
               999px pills (slider troughs, handles, close buttons)
               0     hairline dividers, which GTK would otherwise curl
     border    2px solid @chrome_border
     padding   16px panel gutter
               14px between widget blocks
                4px between sibling cards
     font      "0xProto Nerd Font", "0xProto", monospace at 15px
   ==========================================================================
*/

/* Surfaces, back to front. */
@define-color chrome_bg           {{bg}};
@define-color chrome_bg_alt       {{bg_alt}};
@define-color chrome_surface      {{surface}};
@define-color chrome_surface2     {{surface2}};
@define-color chrome_overlay      {{overlay}};

/* Text. */
@define-color chrome_fg           {{fg}};
@define-color chrome_fg_dim       {{fg_dim}};

/* Accents. chrome_border is the same value hyprland draws its focused window
   border from, so a panel reads as a focused window whichever theme is on. */
@define-color chrome_accent       {{accent}};
@define-color chrome_accent_alt   {{accent_alt}};
@define-color chrome_border       {{border_active}};

/* Status colours, for anything that needs to signal rather than decorate. */
@define-color chrome_red          {{red}};
@define-color chrome_green        {{green}};
@define-color chrome_yellow       {{yellow}};
@define-color chrome_blue         {{blue}};

/* Translucent variants. GTK3 cannot derive an alpha from a @define-color at
   parse time, so these are rendered as literal rgba() rather than computed. */
@define-color chrome_bg_soft      {{bg_rgba}};
@define-color chrome_surface_soft {{surface_rgba}};
@define-color chrome_accent_soft  {{accent_soft}};
